### ISSUE TITLE
Error in Build

### ISSUE THREAD

**Issue by jbest2015** [yurisliepins/ClarifaiCSharp#1]
Visual Studio doesn't like 
clientOptions = options ?? throw new ArgumentNullException(nameof(options));

Getting the following error 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1002	; expected	Clarifai.Core	C:\Users\jb\Source\Repos\ClarifaiCSharp\ClarifaiCSharp\Clarifai.Core\ClarifaiClient.cs	42	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1525	Invalid expression term 'throw'	Clarifai.Core	C:\Users\jb\Source\Repos\ClarifaiCSharp\ClarifaiCSharp\Clarifai.Core\ClarifaiClient.cs	45	Active

**Comment by jbest2015** [comment]
I wound up just changing it to check for nulls with a try catch before it runs, not sure why it doesn't like the syntax.

**Comment by yurisliepins** [comment]
That's C# 7 syntax. Probably need to update Microsoft.Net.Compilers. You can also set the C# version for the compiler in the project properties but it should use the latest by default.
